### ISSUE TITLE
Webpage Looks Dull

### ISSUE THREAD

**Issue by ghost** [degittester/supreme-lamp#2]
The webpage looks dull. It needs a new look. UI update is required.

**Comment by degittester** [comment]
Trying to fix the issue. Kindly wait or make a PR after fixing the issue by yourself Thank You.

**Comment by yashfalke77** [comment]
can i do sir , but please provide me more instruction on how to make it better

**Comment by degittester** [comment]
Visit the website of this repository from the active pages

**Comment by soumyajoydas01** [comment]
@yashfalke77 You may change the stylesheet.
